/** The Disclaimer Form wording in every site language, exported from the frontend dictionaries
 *  (Frontend/src/pages/Waiver.tsx + src/i18n/*.json). Regenerate with the export script when the text changes. */
export type TermsLang = 'en' | 'fr' | 'de' | 'it' | 'ar';
export const TERMS: Record<TermsLang, { clauses: string[]; labels: Record<string, string> }> = {
 "en": {
  "clauses": [
   "Acknowledges that he/the minor Participant has attended the introductory session delivered by the employees/representatives of the Company which is designed to familiarize the attendees with the handling and use of the relevant equipment and accessories with respect to the selected activity (the “Equipment”). The Participant/the Legal Guardians declare being satisfied with such introductory session.",
   "Declares that he/the minor Participant is capable of handling and operating the Equipment and accepts that the use of the Equipment shall be at his/the minor Participant’s own risks.",
   "Accepts that for the duration of the activity, the Equipment shall be under his care and custody (“garde”), until same returned to the Company.",
   "Accepts that the Company reserves the right to claim any incurred costs following any damage of its equipment and/or accessories as a direct result of it not being used in orderly or proper manner or non-conformity with any instructions delivered by the Company’s employees/representatives or not used as a reasonable person would. Further agrees to indemnify the Company in the non-negotiable and minimum sum of Rupees 25,000/- whenever a quad or a buggy is damaged by the acts and doings of the Participant.",
   "Accepts to promptly report to the Company any defect noted in the operation of the Equipment before the start of the activity or at the soonest the defect comes to the knowledge of the Participant. In the absence of any such report, the Company shall consider that the Participant/Legal Guardian accepts that the Equipment has been handed to him/minor Participant in good working condition.",
   "Agrees to ensure that he/the minor Participant shall at all time wear such helmet provided to him/the minor Participant for the purpose of the activity.",
   "Acknowledges having been made aware of the wilderness of the site and of the level of difficulty pertaining to the tracks.",
   "Declares that he/the minor Participant has agreed to participate in the activity voluntarily and has agreed to do so at his/the minor Participant’s own risks. The Legal Guardian hereby expressly gives his consent to the minor Participant’s participation in the selected activity and agrees that the minor Participant shall be under his responsibilities during the course of the activity.",
   "Warrants that he/the minor Participant is physically and mentally able to participate safely in the activity and that he/the minor Participant has no particular health problem and suffers from no handicap whatsoever that may endanger his/the minor Participant’s life or the life of any participant during the course of the activity. The Participant/Legal Guardian furthermore warrants not being/that the minor Participant isn’t under the influence of any alcohol, drugs or medication which may impair/endanger his/the minor Participant’s participation or that of any other participant during the course of the activity.",
   "Acknowledges that it is strictly forbidden to engage/participate in any of the activity whilst pregnant. Acknowledges that he/the minor Participant has been informed of the security measures to be complied with during the course of the activity and accepts the importance of complying with same at all times. The Participant/Legal Guardian therefore expressly agrees to obey/to ensure that the minor Participant obeys such security measures and agrees to comply with all the instructions of the guide(s)/Company’s employees during the course of the activity.",
   "Accepts that non-compliance with the instructions of the guide(s)/Company’s employees during the course of the activity may result in the latter ending the activity forthwith. In such an event, the Participant/Legal Guardian agrees that he shall not be entitled to any reimbursement whatsoever from the Company.",
   "Takes note of and agrees to the strict non-refund policy operated by the Company whenever an activity is cancelled by the Participant after having been booked and payment made, and such activity can be undertaken at that material time. Rainfall or any weather condition cannot and should not account for the cancellation of any activity.",
   "Hereby agrees to be solely responsible for his/the minor Participant’s personal belongings during the course of the activity.",
   "Agrees that the Company, its employees or agents shall not in any way whatsoever be held liable for any physical, moral or material damage that he/the minor Participant may suffer during the course of the activity, save and except where same results from the “major misconduct” of the Company or its employees or agents.",
   "Expressly waives all rights and actions that he may have against the Company, its employees or agents in respect of any claim/s whatsoever that may arise out of or in connection with his/the minor Participant’s participation in the activity, save and except where same results from the “major misconduct” of the Company or its employees or agents.",
   "Undertakes to indemnify and hold harmless the Company, its employees or agents from and against all claims and actions whatsoever which may at any time be suffered or incurred by, or asserted against, any one of them, as a result of or in connection with the acts and doings of the Participant/minor Participant during the latter’s participation in the activity.",
   "Acknowledges that it is strictly forbidden to swim in the park.",
   "Grants the Company the right to send future promotions to the provided email and/or phone number for advertising purposes (optional: tick the box below)."
  ],
  "labels": {
   "title": "DISCLAIMER FORM",
   "company": "Mare Anguilles Farms Ltd (hereinafter referred to as “The Company”)",
   "intro": "The activities booked are hereinafter referred to as the “activity”. Where the context so requires words denoting the singular include the plural and vice versa.",
   "hereby": "The Participant/Legal Guardian hereby:",
   "participant": "Participant",
   "name": "First and last name",
   "birth": "Date of birth",
   "age": "Age on the day of the visit: {n}",
   "height": "Height (cm)",
   "weight": "Weight (kg)",
   "guardian": "Legal Guardian signing for this minor Participant (first and last name)",
   "address": "Address / Hotel",
   "email": "E-mail",
   "phone": "Phone number",
   "nationality": "Nationality",
   "idNumber": "National Identity Card / Passport number (optional)",
   "emergency": "Emergency contact",
   "emName": "Name of contact person in case of emergency",
   "emPhone": "Phone number of the person to contact in case of emergency",
   "medical": "Medical conditions, allergies or injuries the guides should know about (optional)",
   "confirmations": "Confirmations",
   "c_terms": "I have read the Disclaimer Form above and agree to all its clauses on my own behalf or on behalf of the minor Participant.",
   "c_health": "I confirm clauses 9 and 10: the Participant is physically and mentally able to take part, is not pregnant, and is not under the influence of alcohol, drugs or medication.",
   "c_consent": "I confirm clause 8: participation is voluntary and at the Participant’s own risk; as Legal Guardian I consent to the minor Participant taking part and take responsibility for them.",
   "marketing": "Optional (clause 18): the Company may send future promotions to this e-mail address and/or phone number.",
   "sigParticipant": "Signature of the Participant",
   "sigGuardian": "Signature of the Legal Guardian",
   "underGuardian": "UNDER 18 · SIGNED BY GUARDIAN"
  }
 },
 "fr": {
  "clauses": [
   "Reconnaît que lui-même/le Participant mineur a assisté à la séance d’initiation dispensée par les employés/représentants de la Société, destinée à familiariser les participants avec la manipulation et l’utilisation de l’équipement et des accessoires afférents à l’activité choisie (l’« Équipement »). Le Participant/les Tuteurs légaux se déclarent satisfaits de cette séance d’initiation.",
   "Déclare que lui-même/le Participant mineur est capable de manipuler et de conduire l’Équipement et accepte que l’utilisation de l’Équipement se fasse à ses propres risques/aux propres risques du Participant mineur.",
   "Accepte que, pendant toute la durée de l’activité, l’Équipement demeure sous sa surveillance et sa garde (« garde »), jusqu’à sa restitution à la Société.",
   "Accepte que la Société se réserve le droit de réclamer tous les frais encourus à la suite de tout dommage causé à son équipement et/ou à ses accessoires résultant directement d’une utilisation non ordonnée ou inappropriée, du non-respect des instructions données par les employés/représentants de la Société ou d’une utilisation non conforme à celle qu’en ferait une personne raisonnable. Convient en outre d’indemniser la Société de la somme minimale et non négociable de 25 000 roupies (Rs 25,000/-) chaque fois qu’un quad ou un buggy est endommagé par les faits et gestes du Participant.",
   "Accepte de signaler sans délai à la Société tout défaut constaté dans le fonctionnement de l’Équipement avant le début de l’activité ou dès que le défaut est porté à la connaissance du Participant. En l’absence d’un tel signalement, la Société considérera que le Participant/Tuteur légal accepte que l’Équipement lui a été remis/a été remis au Participant mineur en bon état de fonctionnement.",
   "S’engage à veiller à ce que lui-même/le Participant mineur porte à tout moment le casque qui lui est fourni/qui est fourni au Participant mineur aux fins de l’activité.",
   "Reconnaît avoir été informé du caractère sauvage du site et du niveau de difficulté des pistes.",
   "Déclare que lui-même/le Participant mineur a accepté de participer à l’activité de son plein gré et à ses propres risques/aux propres risques du Participant mineur. Le Tuteur légal donne par la présente expressément son consentement à la participation du Participant mineur à l’activité choisie et convient que le Participant mineur demeure sous sa responsabilité pendant toute la durée de l’activité.",
   "Garantit que lui-même/le Participant mineur est physiquement et mentalement apte à participer en toute sécurité à l’activité et que lui-même/le Participant mineur ne présente aucun problème de santé particulier ni aucun handicap, de quelque nature que ce soit, susceptible de mettre en danger sa vie/la vie du Participant mineur ou celle de tout autre participant au cours de l’activité. Le Participant/Tuteur légal garantit en outre ne pas être/que le Participant mineur n’est pas sous l’influence d’alcool, de drogues ou de médicaments susceptibles d’altérer/de compromettre sa participation/la participation du Participant mineur ou celle de tout autre participant au cours de l’activité.",
   "Reconnaît qu’il est strictement interdit de pratiquer l’une quelconque des activités ou d’y participer en état de grossesse. Reconnaît que lui-même/le Participant mineur a été informé des mesures de sécurité à respecter au cours de l’activité et accepte l’importance de s’y conformer à tout moment. Le Participant/Tuteur légal s’engage par conséquent expressément à respecter/à veiller à ce que le Participant mineur respecte ces mesures de sécurité et accepte de se conformer à toutes les instructions du/des guide(s) ou des employés de la Société au cours de l’activité.",
   "Accepte que le non-respect des instructions du/des guide(s) ou des employés de la Société au cours de l’activité puisse entraîner l’arrêt immédiat de l’activité par ces derniers. Dans un tel cas, le Participant/Tuteur légal convient qu’il n’aura droit à aucun remboursement, de quelque nature que ce soit, de la part de la Société.",
   "Prend acte et accepte la politique stricte de non-remboursement appliquée par la Société lorsqu’une activité est annulée par le Participant après avoir été réservée et payée, alors que cette activité peut être réalisée au moment prévu. La pluie ou toute autre condition météorologique ne peut ni ne doit justifier l’annulation d’une activité.",
   "Accepte par la présente d’être seul responsable de ses effets personnels/des effets personnels du Participant mineur au cours de l’activité.",
   "Convient que la Société, ses employés ou ses mandataires ne pourront en aucune manière être tenus responsables de tout dommage physique, moral ou matériel que lui-même/le Participant mineur pourrait subir au cours de l’activité, sauf lorsque ce dommage résulte d’une « faute grave » de la Société, de ses employés ou de ses mandataires.",
   "Renonce expressément à tous droits et actions dont il pourrait disposer à l’encontre de la Société, de ses employés ou de ses mandataires au titre de toute réclamation, quelle qu’elle soit, pouvant découler de sa participation/de la participation du Participant mineur à l’activité ou s’y rapportant, sauf lorsque celle-ci résulte d’une « faute grave » de la Société, de ses employés ou de ses mandataires.",
   "S’engage à indemniser et à garantir la Société, ses employés ou ses mandataires contre toutes réclamations et actions, quelles qu’elles soient, qui pourraient à tout moment être subies ou encourues par l’un d’eux, ou intentées à son encontre, du fait ou à l’occasion des faits et gestes du Participant/Participant mineur pendant la participation de ce dernier à l’activité.",
   "Reconnaît qu’il est strictement interdit de se baigner dans le parc.",
   "Autorise la Société à envoyer de futures offres promotionnelles à l’adresse e-mail et/ou au numéro de téléphone fournis, à des fins publicitaires (facultatif : cochez la case ci-dessous)."
  ],
  "labels": {
   "title": "FORMULAIRE DE DÉCHARGE",
   "company": "Mare Anguilles Farms Ltd (ci-après dénommée « la Société »)",
   "intro": "Les activités réservées sont ci-après dénommées l’« activité ». Lorsque le contexte l’exige, les termes au singulier incluent le pluriel et inversement.",
   "hereby": "Le Participant/Tuteur légal, par la présente :",
   "participant": "Participant",
   "name": "Prénom et nom",
   "birth": "Date de naissance",
   "age": "Âge le jour de la visite : {n}",
   "height": "Taille (cm)",
   "weight": "Poids (kg)",
   "guardian": "Tuteur légal signant pour ce Participant mineur (prénom et nom)",
   "address": "Adresse / Hôtel",
   "email": "E-mail",
   "phone": "Numéro de téléphone",
   "nationality": "Nationalité",
   "idNumber": "Numéro de carte d’identité nationale / de passeport (facultatif)",
   "emergency": "Contact d’urgence",
   "emName": "Nom de la personne à contacter en cas d’urgence",
   "emPhone": "Numéro de téléphone de la personne à contacter en cas d’urgence",
   "medical": "Problèmes de santé, allergies ou blessures que les guides doivent connaître (facultatif)",
   "confirmations": "Confirmations",
   "c_terms": "J’ai lu le Formulaire de décharge ci-dessus et j’en accepte toutes les clauses, en mon nom propre ou au nom du Participant mineur.",
   "c_health": "Je confirme les clauses 9 et 10 : le Participant est physiquement et mentalement apte à participer, n’est pas enceinte et n’est pas sous l’influence de l’alcool, de drogues ou de médicaments.",
   "c_consent": "Je confirme la clause 8 : la participation est volontaire et aux propres risques du Participant ; en tant que Tuteur légal, je consens à la participation du Participant mineur et j’en assume la responsabilité.",
   "marketing": "Facultatif (clause 18) : la Société peut envoyer de futures offres promotionnelles à cette adresse e-mail et/ou à ce numéro de téléphone.",
   "sigParticipant": "Signature du Participant",
   "sigGuardian": "Signature du Tuteur légal",
   "underGuardian": "MOINS DE 18 ANS · SIGNÉE PAR LE TUTEUR"
  }
 },
 "de": {
  "clauses": [
   "Bestätigt, dass er/der minderjährige Teilnehmer an der von den Mitarbeitern/Vertretern des Unternehmens durchgeführten Einführung teilgenommen hat, die dazu dient, die Teilnehmenden mit der Handhabung und Nutzung der für die gewählte Aktivität maßgeblichen Ausrüstung und des Zubehörs (die „Ausrüstung“) vertraut zu machen. Der Teilnehmer/die gesetzlichen Vertreter erklären, mit dieser Einführung zufrieden zu sein.",
   "Erklärt, dass er/der minderjährige Teilnehmer in der Lage ist, die Ausrüstung zu handhaben und zu bedienen, und akzeptiert, dass die Nutzung der Ausrüstung auf eigenes Risiko/auf Risiko des minderjährigen Teilnehmers erfolgt.",
   "Akzeptiert, dass die Ausrüstung für die Dauer der Aktivität seiner Obhut und Verwahrung („garde“) unterliegt, bis sie an das Unternehmen zurückgegeben wird.",
   "Akzeptiert, dass sich das Unternehmen das Recht vorbehält, sämtliche Kosten geltend zu machen, die infolge einer Beschädigung seiner Ausrüstung und/oder seines Zubehörs entstehen, wenn diese unmittelbar auf eine unsachgemäße oder unordentliche Nutzung, auf die Nichtbeachtung der von den Mitarbeitern/Vertretern des Unternehmens erteilten Anweisungen oder auf eine Nutzung zurückzuführen ist, die nicht der einer vernünftigen Person entspricht. Verpflichtet sich ferner, das Unternehmen mit dem nicht verhandelbaren Mindestbetrag von 25.000 Rupien (Rs 25,000/-) zu entschädigen, wann immer ein Quad oder ein Buggy durch das Verhalten des Teilnehmers beschädigt wird.",
   "Akzeptiert, dem Unternehmen jeden im Betrieb der Ausrüstung festgestellten Mangel unverzüglich zu melden, und zwar vor Beginn der Aktivität oder sobald der Mangel dem Teilnehmer bekannt wird. Erfolgt keine solche Meldung, geht das Unternehmen davon aus, dass der Teilnehmer/gesetzliche Vertreter anerkennt, dass ihm/dem minderjährigen Teilnehmer die Ausrüstung in einwandfreiem Betriebszustand übergeben wurde.",
   "Verpflichtet sich sicherzustellen, dass er/der minderjährige Teilnehmer den ihm/dem minderjährigen Teilnehmer für die Aktivität zur Verfügung gestellten Helm jederzeit trägt.",
   "Bestätigt, über den wilden, naturbelassenen Charakter des Geländes und den Schwierigkeitsgrad der Strecken informiert worden zu sein.",
   "Erklärt, dass er/der minderjährige Teilnehmer der Teilnahme an der Aktivität freiwillig zugestimmt hat und dies auf eigenes Risiko/auf Risiko des minderjährigen Teilnehmers tut. Der gesetzliche Vertreter erteilt hiermit ausdrücklich seine Einwilligung zur Teilnahme des minderjährigen Teilnehmers an der gewählten Aktivität und erklärt sich einverstanden, dass der minderjährige Teilnehmer während der Aktivität seiner Verantwortung untersteht.",
   "Versichert, dass er/der minderjährige Teilnehmer körperlich und geistig in der Lage ist, sicher an der Aktivität teilzunehmen, und dass er/der minderjährige Teilnehmer kein besonderes gesundheitliches Problem hat und an keinerlei Behinderung leidet, die sein Leben/das Leben des minderjährigen Teilnehmers oder das Leben eines anderen Teilnehmers während der Aktivität gefährden könnte. Der Teilnehmer/gesetzliche Vertreter versichert ferner, nicht/dass der minderjährige Teilnehmer nicht unter dem Einfluss von Alkohol, Drogen oder Medikamenten steht, die seine Teilnahme/die Teilnahme des minderjährigen Teilnehmers oder die eines anderen Teilnehmers während der Aktivität beeinträchtigen/gefährden könnten.",
   "Bestätigt, dass die Ausübung von bzw. die Teilnahme an jeglicher Aktivität während einer Schwangerschaft strengstens untersagt ist. Bestätigt, dass er/der minderjährige Teilnehmer über die während der Aktivität einzuhaltenden Sicherheitsvorkehrungen informiert wurde, und erkennt an, wie wichtig es ist, diese jederzeit einzuhalten. Der Teilnehmer/gesetzliche Vertreter verpflichtet sich daher ausdrücklich, diese Sicherheitsvorkehrungen zu befolgen/sicherzustellen, dass der minderjährige Teilnehmer sie befolgt, und erklärt sich einverstanden, während der Aktivität alle Anweisungen des/der Guide(s) bzw. der Mitarbeiter des Unternehmens zu befolgen.",
   "Akzeptiert, dass die Nichtbefolgung der Anweisungen des/der Guide(s) bzw. der Mitarbeiter des Unternehmens während der Aktivität dazu führen kann, dass diese die Aktivität unverzüglich beenden. In einem solchen Fall erklärt sich der Teilnehmer/gesetzliche Vertreter damit einverstanden, dass er keinerlei Anspruch auf Rückerstattung gegenüber dem Unternehmen hat.",
   "Nimmt die strikte Nichterstattungsregelung des Unternehmens zur Kenntnis und akzeptiert sie; sie gilt, wenn eine Aktivität nach Buchung und Zahlung vom Teilnehmer storniert wird und diese Aktivität zum betreffenden Zeitpunkt durchführbar ist. Regen oder sonstige Witterungsbedingungen können und dürfen nicht als Grund für die Stornierung einer Aktivität gelten.",
   "Erklärt sich hiermit einverstanden, während der Aktivität allein für seine persönlichen Gegenstände/die persönlichen Gegenstände des minderjährigen Teilnehmers verantwortlich zu sein.",
   "Erklärt sich einverstanden, dass das Unternehmen, seine Mitarbeiter oder Beauftragten in keiner Weise für körperliche, immaterielle oder materielle Schäden haften, die er/der minderjährige Teilnehmer während der Aktivität erleiden könnte, es sei denn, diese sind auf ein „grobes Fehlverhalten“ des Unternehmens, seiner Mitarbeiter oder Beauftragten zurückzuführen.",
   "Verzichtet ausdrücklich auf alle Rechte und Ansprüche, die ihm gegenüber dem Unternehmen, seinen Mitarbeitern oder Beauftragten in Bezug auf jegliche Forderungen zustehen könnten, die sich aus seiner Teilnahme/der Teilnahme des minderjährigen Teilnehmers an der Aktivität ergeben oder damit zusammenhängen, es sei denn, diese sind auf ein „grobes Fehlverhalten“ des Unternehmens, seiner Mitarbeiter oder Beauftragten zurückzuführen.",
   "Verpflichtet sich, das Unternehmen, seine Mitarbeiter oder Beauftragten von allen Forderungen und Klagen jeglicher Art freizustellen und schadlos zu halten, die einem von ihnen zu irgendeinem Zeitpunkt infolge oder im Zusammenhang mit dem Verhalten des Teilnehmers/minderjährigen Teilnehmers während dessen Teilnahme an der Aktivität entstehen, von ihm zu tragen sind oder gegen ihn geltend gemacht werden.",
   "Bestätigt, dass das Schwimmen im Park strengstens untersagt ist.",
   "Räumt dem Unternehmen das Recht ein, künftige Werbeangebote zu Werbezwecken an die angegebene E-Mail-Adresse und/oder Telefonnummer zu senden (optional: Kästchen unten ankreuzen)."
  ],
  "labels": {
   "title": "HAFTUNGSAUSSCHLUSSERKLÄRUNG",
   "company": "Mare Anguilles Farms Ltd (nachfolgend „das Unternehmen“ genannt)",
   "intro": "Die gebuchten Aktivitäten werden nachfolgend als die „Aktivität“ bezeichnet. Soweit der Zusammenhang es erfordert, schließen Begriffe im Singular den Plural ein und umgekehrt.",
   "hereby": "Der Teilnehmer/gesetzliche Vertreter erklärt hiermit Folgendes:",
   "participant": "Teilnehmer",
   "name": "Vor- und Nachname",
   "birth": "Geburtsdatum",
   "age": "Alter am Tag des Besuchs: {n}",
   "height": "Größe (cm)",
   "weight": "Gewicht (kg)",
   "guardian": "Gesetzlicher Vertreter, der für diesen minderjährigen Teilnehmer unterzeichnet (Vor- und Nachname)",
   "address": "Adresse / Hotel",
   "email": "E-Mail",
   "phone": "Telefonnummer",
   "nationality": "Nationalität",
   "idNumber": "Nummer des Personalausweises / Reisepasses (optional)",
   "emergency": "Notfallkontakt",
   "emName": "Name der Kontaktperson im Notfall",
   "emPhone": "Telefonnummer der im Notfall zu kontaktierenden Person",
   "medical": "Erkrankungen, Allergien oder Verletzungen, über die die Guides Bescheid wissen sollten (optional)",
   "confirmations": "Bestätigungen",
   "c_terms": "Ich habe die obige Haftungsausschlusserklärung gelesen und stimme allen ihren Klauseln in meinem eigenen Namen oder im Namen des minderjährigen Teilnehmers zu.",
   "c_health": "Ich bestätige die Klauseln 9 und 10: Der Teilnehmer ist körperlich und geistig in der Lage teilzunehmen, ist nicht schwanger und steht nicht unter dem Einfluss von Alkohol, Drogen oder Medikamenten.",
   "c_consent": "Ich bestätige Klausel 8: Die Teilnahme erfolgt freiwillig und auf eigenes Risiko des Teilnehmers; als gesetzlicher Vertreter willige ich in die Teilnahme des minderjährigen Teilnehmers ein und übernehme die Verantwortung für ihn.",
   "marketing": "Optional (Klausel 18): Das Unternehmen darf künftige Werbeangebote an diese E-Mail-Adresse und/oder Telefonnummer senden.",
   "sigParticipant": "Unterschrift des Teilnehmers",
   "sigGuardian": "Unterschrift des gesetzlichen Vertreters",
   "underGuardian": "UNTER 18 · VOM ERZIEHUNGSBERECHTIGTEN UNTERSCHRIEBEN"
  }
 },
 "it": {
  "clauses": [
   "Riconosce che egli/il Partecipante minorenne ha partecipato alla sessione introduttiva tenuta dai dipendenti/rappresentanti della Società, volta a familiarizzare i partecipanti con la manipolazione e l’uso dell’attrezzatura e degli accessori relativi all’attività prescelta (l’“Attrezzatura”). Il Partecipante/i Tutori legali si dichiarano soddisfatti di tale sessione introduttiva.",
   "Dichiara che egli/il Partecipante minorenne è in grado di maneggiare e utilizzare l’Attrezzatura e accetta che l’uso dell’Attrezzatura avvenga a proprio rischio/a rischio del Partecipante minorenne.",
   "Accetta che, per tutta la durata dell’attività, l’Attrezzatura sia posta sotto la sua cura e custodia (“garde”), fino alla restituzione della stessa alla Società.",
   "Accetta che la Società si riservi il diritto di richiedere il rimborso di tutti i costi sostenuti a seguito di eventuali danni alla propria attrezzatura e/o ai propri accessori derivanti direttamente da un uso non corretto o improprio, dal mancato rispetto delle istruzioni impartite dai dipendenti/rappresentanti della Società o da un uso non conforme a quello di una persona ragionevole. Conviene inoltre di indennizzare la Società con la somma minima e non negoziabile di 25.000 rupie (Rs 25,000/-) ogniqualvolta un quad o un buggy venga danneggiato per fatto del Partecipante.",
   "Accetta di segnalare tempestivamente alla Società qualsiasi difetto riscontrato nel funzionamento dell’Attrezzatura prima dell’inizio dell’attività o non appena il difetto giunga a conoscenza del Partecipante. In assenza di tale segnalazione, la Società riterrà che il Partecipante/Tutore legale accetti che l’Attrezzatura sia stata consegnata a lui/al Partecipante minorenne in buone condizioni di funzionamento.",
   "Si impegna a garantire che egli/il Partecipante minorenne indossi in ogni momento il casco fornito a lui/al Partecipante minorenne ai fini dell’attività.",
   "Riconosce di essere stato informato del carattere selvaggio del sito e del livello di difficoltà dei percorsi.",
   "Dichiara che egli/il Partecipante minorenne ha accettato di partecipare all’attività volontariamente e a proprio rischio/a rischio del Partecipante minorenne. Il Tutore legale presta con la presente il proprio espresso consenso alla partecipazione del Partecipante minorenne all’attività prescelta e conviene che il Partecipante minorenne rimanga sotto la sua responsabilità durante lo svolgimento dell’attività.",
   "Garantisce che egli/il Partecipante minorenne è fisicamente e mentalmente in grado di partecipare in sicurezza all’attività e che egli/il Partecipante minorenne non presenta alcun problema di salute particolare né alcuna disabilità che possa mettere in pericolo la propria vita/la vita del Partecipante minorenne o quella di qualsiasi altro partecipante durante lo svolgimento dell’attività. Il Partecipante/Tutore legale garantisce inoltre di non essere/che il Partecipante minorenne non è sotto l’effetto di alcol, droghe o farmaci che possano compromettere/mettere in pericolo la propria partecipazione/la partecipazione del Partecipante minorenne o quella di qualsiasi altro partecipante durante lo svolgimento dell’attività.",
   "Riconosce che è severamente vietato praticare/partecipare a qualsiasi attività in stato di gravidanza. Riconosce che egli/il Partecipante minorenne è stato informato delle misure di sicurezza da rispettare durante lo svolgimento dell’attività e accetta l’importanza di rispettarle in ogni momento. Il Partecipante/Tutore legale si impegna pertanto espressamente a osservare/a garantire che il Partecipante minorenne osservi tali misure di sicurezza e accetta di attenersi a tutte le istruzioni della/delle guida/e o dei dipendenti della Società durante lo svolgimento dell’attività.",
   "Accetta che il mancato rispetto delle istruzioni della/delle guida/e o dei dipendenti della Società durante lo svolgimento dell’attività possa comportare l’immediata interruzione dell’attività da parte di questi ultimi. In tal caso, il Partecipante/Tutore legale conviene che non avrà diritto ad alcun rimborso, di qualsiasi natura, da parte della Società.",
   "Prende atto e accetta la rigorosa politica di non rimborso applicata dalla Società qualora un’attività venga annullata dal Partecipante dopo la prenotazione e il pagamento, e tale attività possa essere svolta nel momento previsto. La pioggia o qualsiasi altra condizione meteorologica non può e non deve giustificare l’annullamento di alcuna attività.",
   "Accetta con la presente di essere l’unico responsabile dei propri effetti personali/degli effetti personali del Partecipante minorenne durante lo svolgimento dell’attività.",
   "Conviene che la Società, i suoi dipendenti o incaricati non potranno in alcun modo essere ritenuti responsabili di qualsiasi danno fisico, morale o materiale che egli/il Partecipante minorenne possa subire durante lo svolgimento dell’attività, salvo il caso in cui tale danno derivi da una “colpa grave” della Società, dei suoi dipendenti o incaricati.",
   "Rinuncia espressamente a tutti i diritti e le azioni che possa vantare nei confronti della Società, dei suoi dipendenti o incaricati in relazione a qualsiasi pretesa derivante da o connessa alla sua partecipazione/alla partecipazione del Partecipante minorenne all’attività, salvo il caso in cui essa derivi da una “colpa grave” della Società, dei suoi dipendenti o incaricati.",
   "Si impegna a indennizzare e manlevare la Società, i suoi dipendenti o incaricati da qualsiasi pretesa e azione che possa in qualsiasi momento essere subita o sostenuta da uno di essi, o fatta valere nei suoi confronti, in conseguenza o in relazione al comportamento del Partecipante/Partecipante minorenne durante la partecipazione di quest’ultimo all’attività.",
   "Riconosce che è severamente vietato nuotare nel parco.",
   "Concede alla Società il diritto di inviare future promozioni all’indirizzo e-mail e/o al numero di telefono forniti a fini pubblicitari (facoltativo: spuntare la casella sottostante)."
  ],
  "labels": {
   "title": "MODULO DI ESONERO DI RESPONSABILITÀ",
   "company": "Mare Anguilles Farms Ltd (di seguito denominata “la Società”)",
   "intro": "Le attività prenotate sono di seguito denominate l’“attività”. Ove il contesto lo richieda, i termini al singolare includono il plurale e viceversa.",
   "hereby": "Il Partecipante/Tutore legale con la presente:",
   "participant": "Partecipante",
   "name": "Nome e cognome",
   "birth": "Data di nascita",
   "age": "Età il giorno della visita: {n}",
   "height": "Altezza (cm)",
   "weight": "Peso (kg)",
   "guardian": "Tutore legale che firma per questo Partecipante minorenne (nome e cognome)",
   "address": "Indirizzo / Hotel",
   "email": "E-mail",
   "phone": "Numero di telefono",
   "nationality": "Nazionalità",
   "idNumber": "Numero di carta d’identità / passaporto (facoltativo)",
   "emergency": "Contatto di emergenza",
   "emName": "Nome della persona da contattare in caso di emergenza",
   "emPhone": "Numero di telefono della persona da contattare in caso di emergenza",
   "medical": "Condizioni mediche, allergie o infortuni che le guide dovrebbero conoscere (facoltativo)",
   "confirmations": "Conferme",
   "c_terms": "Ho letto il Modulo di esonero di responsabilità di cui sopra e ne accetto tutte le clausole, in nome proprio o per conto del Partecipante minorenne.",
   "c_health": "Confermo le clausole 9 e 10: il Partecipante è fisicamente e mentalmente in grado di partecipare, non è in stato di gravidanza e non è sotto l’effetto di alcol, droghe o farmaci.",
   "c_consent": "Confermo la clausola 8: la partecipazione è volontaria e a rischio del Partecipante; in qualità di Tutore legale acconsento alla partecipazione del Partecipante minorenne e me ne assumo la responsabilità.",
   "marketing": "Facoltativo (clausola 18): la Società può inviare future promozioni a questo indirizzo e-mail e/o numero di telefono.",
   "sigParticipant": "Firma del Partecipante",
   "sigGuardian": "Firma del Tutore legale",
   "underGuardian": "MINORE DI 18 ANNI · FIRMATA DAL TUTORE"
  }
 },
 "ar": {
  "clauses": [
   "يقر بأنه/بأن المشارك القاصر قد حضر الجلسة التعريفية التي قدمها موظفو الشركة أو ممثلوها، والمصممة لتعريف الحاضرين بكيفية التعامل مع المعدات والملحقات الخاصة بالنشاط المختار واستخدامها («المعدات»). ويعلن المشارك/الأوصياء القانونيون رضاهم عن هذه الجلسة التعريفية.",
   "يعلن أنه/أن المشارك القاصر قادر على التعامل مع المعدات وتشغيلها، ويقبل أن يكون استخدام المعدات على مسؤوليته الخاصة/على مسؤولية المشارك القاصر الخاصة.",
   "يقبل أن تكون المعدات، طوال مدة النشاط، تحت رعايته وحراسته («garde»)، إلى حين إعادتها إلى الشركة.",
   "يقبل أن الشركة تحتفظ بحقها في المطالبة بأي تكاليف تتكبدها نتيجة أي ضرر يلحق بمعداتها و/أو ملحقاتها بسبب مباشر يتمثل في عدم استخدامها بطريقة منظمة أو سليمة، أو عدم الامتثال لأي تعليمات صادرة عن موظفي الشركة أو ممثليها، أو استخدامها على نحو لا يستخدمه الشخص العاقل. ويوافق كذلك على تعويض الشركة بمبلغ أدنى غير قابل للتفاوض قدره 25,000 روبية (Rs 25,000/-) كلما تعرضت دراجة رباعية (كواد) أو عربة باغي للضرر بسبب أفعال المشارك وتصرفاته.",
   "يقبل إبلاغ الشركة فورًا بأي عيب يُلاحظ في تشغيل المعدات قبل بدء النشاط أو في أقرب وقت يصل فيه العيب إلى علم المشارك. وفي حال عدم وجود مثل هذا الإبلاغ، تعتبر الشركة أن المشارك/الوصي القانوني يقر بأن المعدات قد سُلِّمت إليه/إلى المشارك القاصر في حالة تشغيل جيدة.",
   "يوافق على ضمان أن يرتدي هو/المشارك القاصر في جميع الأوقات الخوذة المقدمة له/للمشارك القاصر لأغراض النشاط.",
   "يقر بأنه قد أُحيط علمًا بالطبيعة البرية للموقع وبمستوى صعوبة المسارات.",
   "يعلن أنه/أن المشارك القاصر قد وافق على المشاركة في النشاط طوعًا، وعلى أن يكون ذلك على مسؤوليته الخاصة/على مسؤولية المشارك القاصر الخاصة. ويمنح الوصي القانوني بموجب هذا موافقته الصريحة على مشاركة المشارك القاصر في النشاط المختار ويوافق على أن يكون المشارك القاصر تحت مسؤوليته طوال مدة النشاط.",
   "يضمن أنه/أن المشارك القاصر قادر جسديًا وذهنيًا على المشاركة بأمان في النشاط، وأنه/أن المشارك القاصر لا يعاني من أي مشكلة صحية خاصة ولا من أي إعاقة من أي نوع كان قد تعرض حياته/حياة المشارك القاصر أو حياة أي مشارك آخر للخطر أثناء النشاط. ويضمن المشارك/الوصي القانوني كذلك أنه ليس/أن المشارك القاصر ليس تحت تأثير أي كحول أو مخدرات أو أدوية قد تُضعف/تُعرض للخطر مشاركته/مشاركة المشارك القاصر أو مشاركة أي مشارك آخر أثناء النشاط.",
   "يقر بأنه يُحظر حظرًا تامًا ممارسة أي من الأنشطة أو المشاركة فيها أثناء الحمل. ويقر بأنه/بأن المشارك القاصر قد أُبلغ بتدابير السلامة الواجب الالتزام بها أثناء النشاط ويقبل أهمية الالتزام بها في جميع الأوقات. وعليه، يوافق المشارك/الوصي القانوني صراحةً على الامتثال لتدابير السلامة هذه/على ضمان امتثال المشارك القاصر لها، ويوافق على الالتزام بجميع تعليمات المرشد (المرشدين) أو موظفي الشركة أثناء النشاط.",
   "يقبل أن عدم الامتثال لتعليمات المرشد (المرشدين) أو موظفي الشركة أثناء النشاط قد يؤدي إلى قيام هؤلاء بإنهاء النشاط فورًا. وفي هذه الحالة، يوافق المشارك/الوصي القانوني على أنه لا يحق له الحصول على أي استرداد من أي نوع كان من الشركة.",
   "يحيط علمًا بسياسة عدم الاسترداد الصارمة التي تطبقها الشركة ويوافق عليها، وذلك كلما ألغى المشارك نشاطًا بعد حجزه ودفع قيمته، وكان من الممكن تنفيذ هذا النشاط في الوقت المحدد له. ولا يمكن ولا يجوز اعتبار هطول الأمطار أو أي ظرف جوي آخر مبررًا لإلغاء أي نشاط.",
   "يوافق بموجب هذا على أن يكون وحده المسؤول عن متعلقاته الشخصية/المتعلقات الشخصية للمشارك القاصر أثناء النشاط.",
   "يوافق على أن الشركة أو موظفيها أو وكلاءها لن يتحملوا بأي شكل من الأشكال المسؤولية عن أي ضرر جسدي أو معنوي أو مادي قد يلحق به/بالمشارك القاصر أثناء النشاط، باستثناء ما ينشأ عن «سوء سلوك جسيم» من جانب الشركة أو موظفيها أو وكلائها.",
   "يتنازل صراحةً عن جميع الحقوق والدعاوى التي قد تكون له في مواجهة الشركة أو موظفيها أو وكلائها فيما يتعلق بأي مطالبة من أي نوع كان قد تنشأ عن مشاركته/مشاركة المشارك القاصر في النشاط أو تتصل بها، باستثناء ما ينشأ عن «سوء سلوك جسيم» من جانب الشركة أو موظفيها أو وكلائها.",
   "يتعهد بتعويض الشركة أو موظفيها أو وكلائها وإبراء ذمتهم من جميع المطالبات والدعاوى من أي نوع كان التي قد يتكبدها أو يتحملها أي منهم أو تُرفع ضده في أي وقت نتيجة أفعال المشارك/المشارك القاصر وتصرفاته أثناء مشاركة هذا الأخير في النشاط أو فيما يتصل بها.",
   "يقر بأن السباحة في المنتزه محظورة حظرًا تامًا.",
   "يمنح الشركة الحق في إرسال عروض ترويجية مستقبلية إلى عنوان البريد الإلكتروني و/أو رقم الهاتف المقدمين لأغراض إعلانية (اختياري: ضع علامة في المربع أدناه)."
  ],
  "labels": {
   "title": "نموذج إخلاء المسؤولية",
   "company": "Mare Anguilles Farms Ltd (ويُشار إليها فيما يلي بـ«الشركة»)",
   "intro": "يُشار إلى الأنشطة المحجوزة فيما يلي بـ«النشاط». وحيثما يقتضي السياق، تشمل الكلمات الدالة على المفرد الجمع والعكس صحيح.",
   "hereby": "يقر المشارك/الوصي القانوني بموجب هذا بما يلي:",
   "participant": "المشارك",
   "name": "الاسم الأول واسم العائلة",
   "birth": "تاريخ الميلاد",
   "age": "العمر يوم الزيارة: {n}",
   "height": "الطول (cm)",
   "weight": "الوزن (kg)",
   "guardian": "الوصي القانوني الموقّع عن هذا المشارك القاصر (الاسم الأول واسم العائلة)",
   "address": "العنوان / الفندق",
   "email": "البريد الإلكتروني",
   "phone": "رقم الهاتف",
   "nationality": "الجنسية",
   "idNumber": "رقم بطاقة الهوية الوطنية / جواز السفر (اختياري)",
   "emergency": "جهة اتصال الطوارئ",
   "emName": "اسم الشخص الذي يُتصل به في حالة الطوارئ",
   "emPhone": "رقم هاتف الشخص الذي يُتصل به في حالة الطوارئ",
   "medical": "الحالات الصحية أو الحساسية أو الإصابات التي ينبغي أن يعرفها المرشدون (اختياري)",
   "confirmations": "التأكيدات",
   "c_terms": "لقد قرأت نموذج إخلاء المسؤولية أعلاه وأوافق على جميع بنوده بالأصالة عن نفسي أو نيابةً عن المشارك القاصر.",
   "c_health": "أؤكد البندين 9 و10: المشارك قادر جسديًا وذهنيًا على المشاركة، وليس حاملًا، وليس تحت تأثير الكحول أو المخدرات أو الأدوية.",
   "c_consent": "أؤكد البند 8: المشاركة طوعية وعلى مسؤولية المشارك الخاصة؛ وبصفتي الوصي القانوني أوافق على مشاركة المشارك القاصر وأتحمل المسؤولية عنه.",
   "marketing": "اختياري (البند 18): يجوز للشركة إرسال عروض ترويجية مستقبلية إلى عنوان البريد الإلكتروني هذا و/أو رقم الهاتف هذا.",
   "sigParticipant": "توقيع المشارك",
   "sigGuardian": "توقيع الوصي القانوني",
   "underGuardian": "دون 18 عامًا · وقّعه الولي"
  }
 }
};
